### ISSUE TITLE
Usage in angular app

### ISSUE THREAD

**Issue by DrWifey** [run27017/json-to-table#10]
I want to use this library in my angular application. 
I do
```
import { jsonToHTMLTable } from 'nested-json-to-table';
// also tried 
// declare var require: any;
// const { jsonToHTMLTable } = require('nested-json-to-table');
```
But I'm getting an error:
```
ERROR in ./node_modules/nested-json-to-table/lib/jsonToHTMLTable/node.js
Module not found: Error: Can't resolve 'fs' in '/home/frankie/work/projects/brainstorm/src/main/frontend/node_modules/nested-json-to-table/lib/jsonToHTMLTable'
```
Could you please help me to solve this?

**Comment by run27017** [comment]
Published, the new version is 1.0.5

**Comment by DrWifey** [comment]
Thank you, but I still can't get it working. I'm getting an error:
```
HomeComponent_Host.ngfactory.js? [sm]:1 ERROR ReferenceError: global is not defined
    at push../node_modules/nested-json-to-table/lib/jsonToHTMLTable/index.js.module.exports (index.js:9)
    at HomeComponent.push../src/app/components/home/home.component.ts.HomeComponent.ngOnInit (home.component.ts:65)
    at checkAndUpdateDirectiveInline (core.js:21097)
    at checkAndUpdateNodeInline (core.js:29495)
    at checkAndUpdateNode (core.js:29457)
    at debugCheckAndUpdateNode (core.js:30091)
    at debugCheckDirectivesFn (core.js:30051)
    at Object.eval [as updateDirectives] (HomeComponent_Host.ngfactory.js? [sm]:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:30043)
    at checkAndUpdateView (core.js:29439)
```

Also the previous error now is warning :smile:, but maybe this was done on purpose...

**Comment by run27017** [comment]
You can pass a option `format: 'dom'` to tell jsonToHTMLTable and it will generate a html table dom. There is a hole in current version, and I will fix it in next version.

You say that there is a warning about `require('fs')` now in angular cli? Maybe it will be also fixed up in next version.

**Comment by run27017** [comment]
I have published a new version '1.0.6' and it will resolve your issue about `global`. But now, you should resolve `fs` by yourself, which add following lines to your webpack config:

```javascript
  externals: {
    fs: 'fs'
  }

```

The principle is that I requires `fs` in my code, but it only supplrt node environment. Thus if you are in browser environment, your webpack config should not resolve `fs` in advance.

Maybe more work than before. Best wish!

**Comment by DrWifey** [comment]
Seems I got it working, thank you!
As a feature request, would be great if you add possibility to set some css options, when creating table.
For now I made it this way:
`tableHtml.className += 'ui celled selectable blue compact table';`

**Comment by run27017** [comment]
> Seems I got it working, thank you!
> As a feature request, would be great if you add possibility to set some css options, when creating table.
> For now I made it this way:
> `tableHtml.className += 'ui celled selectable blue compact table';`

Ok，I will add this feature in the future, you could watch the repository to follow the precedure. I'll close the issue now. If you encounter relative bugs about this issue, you could reopen it. Nice enjoyment!
