### ISSUE TITLE
如果某个字段是数组，解析会出现bug

### ISSUE THREAD

**Issue by Shurlormes** [run27017/json-to-table#11]
```
const data = [
  {
    name: '张三',
    hobby: [
      "看书", "看电影", "打篮球"
    ],
  },
  {
    name: '李四',
    hobby: [
      "爬山", "看书"
    ],
  }
]
```
![PMR4{C1{_4FFBQG)} (O 6J](https://user-images.githubusercontent.com/22904862/100703284-29aea600-33de-11eb-86e8-d6b30d5381ce.png)

**Comment by run27017** [comment]
对不起，这几天没有注意到 GitHub 的提醒。现在已经修复，见版本 v1.0.7.
