### ISSUE TITLE
string value with style

### ISSUE THREAD

**Issue by lmdc45** [run27017/json-to-table#12]
Is it possible to change the style of cell (ie background color of a 'td'), or where would be the best place in the code to implement styling?
Would be based on a '_styles' object per row, indicating the cell name containing style attribute, like so (like style attribute given by XLSX package):
```

const data = [
  {
    name: 'Jim',
    age: 18,
    courses: [
      { title: 'English', score: 87 },
      { title: 'Chinese', score: 67 }
    ],
   _style:{
     name:{bgColor:{rgb:''92D050''}}
   }
  },
  {
    name: 'Lucy',
    age: 17,
    courses: [
      { title: 'Math', score: 97 },
      { title: 'Music', score: 77 },
      { title: 'Gym', score: 57 }
    ],
 _style:{
     name:{bgColor:{rgb:''92D080''}}
   }
  }
]
```
`

**Comment by run27017** [comment]
The nice place holding the styles is the props definition. You can define the common style like this way:

```javascript
const props = [ { key: 'a', style: 'background: blue;' }, { key: 'b', class: 'highlight' } ]

const data = [
  { a: 1, b: 2, c: 3, d: 4, e: 5 },
  { a: 6, b: 7, c: 8, d: 9, e: 10 }
]
const tableHTML = jsonToHTMLTable(data, props)
```

And then use jsonToHTMLTable to render it. However, **it is just a idea but not implemented**.
