### ISSUE TITLE
列表中的object内字段可能为空的

### ISSUE THREAD

**Issue by zwtgit** [run27017/json-to-table#15]
如图代码：
`[
      {
        'a': '34',
        'b': [
          {
            'c': '32',
            'd': '435',
            'e': '0.0'
          }
        ]
      },
      {
        'a': '42',
        'b': []
      }
    ]`
![image](https://user-images.githubusercontent.com/22927679/103736893-18376a00-502c-11eb-885c-66bd82299e74.png)
当数组第二项的b为空时，
![image](https://user-images.githubusercontent.com/22927679/103736942-30a78480-502c-11eb-88d1-911825cc48e1.png)

###   版本： "nested-json-to-table": "^1.0.7",

**Comment by run27017** [comment]
已修复，更新版本 1.0.8

**Comment by zwtgit** [comment]
> 已修复，更新版本 1.0.8

十分感谢作者~
