### ISSUE TITLE
能否提供反向转换的工具

### ISSUE THREAD

**Issue by marklion** [run27017/json-to-table#17]
可能更多的需求是：读取json->转换成execl->编辑excel->转换成json->存json

多谢了

**Comment by run27017** [comment]
这个功能需要评估后才能决定，也许以后会上。主要考虑两个方面：

1. 反向转换难度较大；
2. 该工具主要用于展示表格数据的，原本不打算反向编辑使用。它是将 JSON 数据转化为其他格式的数据用于展示，如 HTML Table、Excel 等，这些工具里只有 Excel 才能编辑。

总之，未来再看吧。我调研了一下能够操作 Excel 的工具，包括 [XSLX](https://www.npmjs.com/package/xlsx)，它能够读取和写入 Excel 文件。缺点就是 API 太底层，通用性不高，每个项目都需要专门的处理。
