### ISSUE TITLE
希望在json转为的时候就为其指定某列的classname或者其他属性

### ISSUE THREAD

**Issue by keet3r** [run27017/json-to-table#27]
可以通过prop参数来指定吗？

**Comment by run27017** [comment]
我提供了新项目，为标签添加了指定 props 的功能，如果不满足需求，可在新项目下提交 ISSUE. 新项目地址：

> https://github.com/yetrun/json5-to-table

**Comment by yetrun** [comment]
发现可以转让项目，我把之前的项目转让过来了，地址仍然是：

> https://github.com/yetrun/json5-to-table

所以不用重复 star 了。

**Comment by yetrun** [comment]
> @yetrun @run27017
> 你好, 项目转移后您清除了之前的release. 我从web.archive.org只下载到了您的1.0.6版本json-to-table.min.js.
> 我想问一下可否提供 v1 分支下1.0.5、1.0.7、1.0.8版本的 json-to-table.min.js?

我提供了 1.0.7、1.0.8、1.0.11 版本的打包文件。其中 1.0.11 与 1.0.8 一样，只是 1.0.11 将所有的依赖包更新到最新。
所有打包文件可在 `v1` 分支的 `dist` 目录查看到：

> https://github.com/yetrun/json5-to-table/tree/v1/dist

不过还是建议你及时用到新版的库 `json5-to-table`，因为旧版本分支会在预计一年后不再维护并删掉。如果新库有什么不如意的地方，请及时提交 ISSUE 以便于我改进。万分感谢！
