### ISSUE TITLE
在线工具问题和v1报错问题

### ISSUE THREAD

**Issue by Dealtz** [run27017/json-to-table#6]
问题一：
您好，我上次曾咨询您在线转换工具相关问题。
请问您还在维护此工具吗？
目前https://json-to-table.run27.top/ 已经404，请问您是否继续提供服务？
若不再提供，可否将该网页源码开源？

问题二：
v1版本可能仍然存在bug，我使用的是../dist/json-to-table.min.js这个文件。
一段合法的json（可以通过JSON.parse()转成js对象，因此可保证无json语法格式错误）在调用jsonToHTMLTable()时，报错：
【TypeError: Cannot read property 'd' of undefined】
该段Json来自苹果服务器，由于涉及个人信息在这无法提供给您复现。不过可以提供您获取方法：
该json返回自【https://p24-buy.itunes.apple.com/commerce/account/purchases?isJsonApiFormat=true&page=1 】，是App Store中Apple ID的购买记录。PC端iTunes在【账户】->【查看我的账户】->【购买记录】->【显示全部】，移动端在【iTunes Store 与 App Store】->【Apple ID】->【查看Apple ID】->【购买记录】中。

Best Wishes！

**Comment by run27017** [comment]
第一个问题，网页工具已经停掉了，但是可以提供源码：

> https://gitee.com/run27017/nested-json-to-table-webapp

第二个问题，你的 JSON 文本我没办法拿到啊。你可以尝试在你的 JSON 中，将关键信息抹掉后，发到这个 issue 里来；或者也可以私发给我邮箱：

> run27017[AT]126.com

**Comment by Dealtz** [comment]
> 第一个问题，网页工具已经停掉了，但是可以提供源码：
> 
> > https://gitee.com/run27017/nested-json-to-table-webapp
> 
> 第二个问题，你的 JSON 文本我没办法拿到啊。你可以尝试在你的 JSON 中，将关键信息抹掉后，发到这个 issue 里来；或者也可以私发给我邮箱：
> 
> > run27017[AT]126.com

这样吧，我根据报错信息按照苹果的格式修改了一下https://github.com/run27017/json-to-table/blob/v1/demo/index.js里的data样例，能够复现该操作，这样应该能帮你简化一下json文件：

[
  {
    "a": 1,
    "b": [
      { "d": 2, "e": 3 },
      { "d": 4, "e": 5 }
    ],
    "c": [
      { "d": 6, "e": 17, "f": 18 },
      { "d": 9, "e": 10, "f": 11 },
      { "d": 9, "e": 13, "f": 14, "methods": [
          { "d": "价格", "name": "CNCN" }
        ]
      }
    ]
  }
]

**Comment by run27017** [comment]
已经修复了，安装版本 1.0.2.

另外，一个小建议，代码的部分放在三反引号之间，例如：

    ```json
    [
      {
        "a": 1,
        "b": [
        { "d": 2, "e": 3 },
        { "d": 4, "e": 5 },
      ...
    ]
    ```

显示更漂亮：

```json5
[
  {
    "a": 1,
    "b": [
    { "d": 2, "e": 3 },
    { "d": 4, "e": 5 },
 // ...
]
```

**Comment by Dealtz** [comment]
> 已经修复了，安装版本 1.0.2.


感谢您的修复!
此外, 我在使用新版本时又发现了一个BUG, JSON数据同样来自苹果服务器.
我模仿其内容构建了一个测试样本, 内容如下:
```
[
  {
    "a": [
      {
        "alerts": [],
        "d": 6,
        "e": 17,
        "f": 18
      },
      {
        "d": 9,
        "e": 10,
        "f": 11
      },
      {
        "d": 9,
        "e": 13,
        "f": 14
      }
    ]
  }
]
```
在1.0.2版本渲染得到的表格为:
![01](https://user-images.githubusercontent.com/38786580/88459245-75988e00-cec6-11ea-838d-8a10bb844b52.png)
私以为正确的处理应该为:
![02](https://user-images.githubusercontent.com/38786580/88459252-83e6aa00-cec6-11ea-886f-c882c682f7ae.png)
因此再次向您提交一个bug.

**Comment by run27017** [comment]
> > 已经修复了，安装版本 1.0.2.
> 
> 感谢您的修复!
> 此外, 我在使用新版本时又发现了一个BUG, JSON数据同样来自苹果服务器.
> 我模仿其内容构建了一个测试样本, 内容如下:
> 
> ```
> [
>   {
>     "a": [
>       {
>         "alerts": [],
>         "d": 6,
>         "e": 17,
>         "f": 18
>       },
>       {
>         "d": 9,
>         "e": 10,
>         "f": 11
>       },
>       {
>         "d": 9,
>         "e": 13,
>         "f": 14
>       }
>     ]
>   }
> ]
> ```
> 
> 在1.0.2版本渲染得到的表格为:
> ![01](https://user-images.githubusercontent.com/38786580/88459245-75988e00-cec6-11ea-838d-8a10bb844b52.png)
> 私以为正确的处理应该为:
> ![02](https://user-images.githubusercontent.com/38786580/88459252-83e6aa00-cec6-11ea-886f-c882c682f7ae.png)
> 因此再次向您提交一个bug.

问题在新版本（1.0.3）中修复了。

**Comment by Dealtz** [comment]
> 第一个问题，网页工具已经停掉了，但是可以提供源码：
> 
> > https://gitee.com/run27017/nested-json-to-table-webapp
> 


@yetrun @run27017  不好意思打扰了, 请问还能够提供网页工具的源码吗? 我不小心删除了当时下载的源码, 现在链接失效, 您已经删除在gitee的nested-json-to-table-webapp仓库了. 
不胜感激!

**Comment by yetrun** [comment]
@Dealtz 额，确实删掉了。不过我又私自写了一个新的仓库，用于部署线上工具的：

> https://github.com/yetrun/json-to-table-webapp
