### ISSUE TITLE
JSON中值未空的话，生成失败；

### ISSUE THREAD

**Issue by LiCong2016** [run27017/json-to-table#9]
JSON中值未空的话，生成失败；
function simplifyObject (data) {
  if (Array.isArray(data)) {
    const simpleObjects = data.map(val => simplifyObject(val))
    return merge({}, ...simpleObjects)
  }

  const object = {}
  Object.keys(data).forEach(key => {
    const val = data[key]
    if (val != null && typeof val === 'object') {
      object[key] = simplifyObject(val)
    } else {
      object[key] = true
    }
  })
  return object
}
修改其中： if (val != null && typeof val === 'object') 即可。

**Comment by run27017** [comment]
这段代码我已经忘记原始的意思了，你能提供一个具体的调用失败的例子给我吗？

**Comment by run27017** [comment]
这段代码我已经忘记原始的意思了，你能提供一个具体的调用失败的例子给我吗？

另外，将代码放在两个三引号之间，缩进更好看。例如：

    ```json
    {
        "key": "value"
    }
    ```
```json
{
    "key": "value"
}
```

**Comment by run27017** [comment]
这段代码我已经忘记原始的意思了，你能提供一个具体的调用失败的例子给我吗？

另外，将代码放在两个三引号之间，缩进更好看。例如：

    ```json
    {
        "key": "value"
    }
    ```
```json
{
    "key": "value"
}
```

**Comment by LiCong2016** [comment]
```
{
    "sysconf": {
        "hosts": [
            {
                "key": "node001",
                "value": "192.168.0.1"
            },
            {
                "key": null,
                "value": "192.168.0.2"
            }
        ]
    }
}
```
比如，上面一个JSON，第二个key是null的时候，程序会报错误的。我自己修改了你的源码：lib/jsonToTable/generateProps.js，如下：
```
function simplifyObject (data) {
  if (Array.isArray(data)) {
    const simpleObjects = data.map(val => simplifyObject(val))
    return merge({}, ...simpleObjects)
  }

  const object = {}
  Object.keys(data).forEach(key => {
    const val = data[key]
    if (val != null && typeof val === 'object') {
      object[key] = simplifyObject(val)
    } else {
      object[key] = true
    }
  })
  return object
}
```
我修改了这个方法中的第二个if，修改成：if (val != null && typeof val === 'object') ，和你原来不一样的。
可以解决值为null的问题！

**Comment by run27017** [comment]
@LiCong2016  谢谢提醒，已经修复了，发布了一个小版本 1.0.4，你检查一下。

**Comment by Dealtz** [comment]
> @LiCong2016 谢谢提醒，已经修复了，发布了一个小版本 1.0.4，你检查一下。

1.0.4的这次提交没有发布新的json-to-table.min.js, 是忘记了吗?

**Comment by run27017** [comment]
@Dealtz @LiCong2016 

本来不想管打包的事的，因为现在发布的包都过大（1.1M 左右）。不过既然你提到了，那我继续提供打好的包，现在统一放在 GitHub 的 Release 页面下：

> https://github.com/run27017/json-to-table/releases/tag/v1.0.4

另外，如果条件允许，使用 npm 或 yarn 安装，最好。

**Comment by Dealtz** [comment]
> @Dealtz @LiCong2016
> 
> 本来不想管打包的事的，因为现在发布的包都过大（1.1M 左右）。不过既然你提到了，那我继续提供打好的包，现在统一放在 GitHub 的 Release 页面下：
> 
> > https://github.com/run27017/json-to-table/releases/tag/v1.0.4
> 
> 另外，如果条件允许，使用 npm 或 yarn 安装，最好。

好的，感谢提供
